#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<EOF
SELECT 'CREATE DATABASE "${POSTGRES_DATABASE_MOBILE}"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${POSTGRES_DATABASE_MOBILE}')\gexec
SELECT 'CREATE DATABASE "${POSTGRES_DATABASE_CLOTHES}"'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${POSTGRES_DATABASE_CLOTHES}')\gexec
EOF
