events {}

http {
  resolver 127.0.0.11 valid=10s ipv6=off;

  server {
    listen 80;

    location /api/customer/ {
      set $customer_upstream customer-service:8000;
      rewrite ^/api/customer/(.*)$ /$1 break;
      proxy_pass http://$customer_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/staff/ {
      set $staff_upstream staff-service:8000;
      rewrite ^/api/staff/(.*)$ /$1 break;
      proxy_pass http://$staff_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/laptops/ {
      set $laptop_upstream laptop-service:8000;
      rewrite ^/api/laptops/(.*)$ /api/$1 break;
      proxy_pass http://$laptop_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/mobiles/ {
      set $mobile_upstream mobile-service:8000;
      rewrite ^/api/mobiles/(.*)$ /api/$1 break;
      proxy_pass http://$mobile_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/clothes/ {
      set $clothes_upstream clothes-service:8000;
      rewrite ^/api/clothes/(.*)$ /api/$1 break;
      proxy_pass http://$clothes_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /staff/ {
      set $frontend_staff_upstream frontend-staff:3000;
      proxy_pass http://$frontend_staff_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /assets/ {
      set $frontend_customer_upstream frontend-customer:3000;
      proxy_pass http://$frontend_customer_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /favicon.svg {
      set $frontend_customer_upstream frontend-customer:3000;
      proxy_pass http://$frontend_customer_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
      set $frontend_customer_upstream frontend-customer:3000;
      proxy_pass http://$frontend_customer_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
